#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

VERSION="2.2.0"
URL="http://symfony.com/get/Symfony_Standard_Vendors_${VERSION}.tgz"

dl $URL /usr/local/src

