#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC=/usr/local/src
VERSION="4.1.0"

# Download Composer
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# Download Laravel
dl https://github.com/laravel/laravel/archive/v${VERSION}.zip $SRC
mv $SRC/v${VERSION}.zip $SRC/laravel.zip