#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

# Download Composer
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer

# Download Laravel code from github
VERSION="4.1.0"
URL="https://github.com/laravel/laravel/archive/v$VERSION.zip"
dl $URL /var/www/laravel

