#!/bin/sh -ex

SRC=/usr/local/src
NAME=laravel
WEBROOT=/var/www/laravel

DB_NAME=laravel
DB_USER=laravel
DB_PASS=$(mcookie)

# unpack laravel zip
unzip -q $SRC/$NAME.zip -d $(dirname $WEBROOT)
mv $(dirname $WEBROOT)/laravel* $WEBROOT
chown -R www-data:www-data $WEBROOT
rm $SRC/$NAME.zip

# install laravel dependencies
cd $WEBROOT
composer self-update
composer install

# workaround innodb crap during build!
rm -f /var/lib/mysql/ib_logfile*

# start mysql server
/etc/init.d/mysql start

# create the database and user
mysql --defaults-extra-file=/etc/mysql/debian.cnf <<EOF
CREATE DATABASE $DB_NAME;
GRANT SELECT,INSERT,UPDATE,DELETE,CREATE,DROP,ALTER
ON $DB_NAME.*
TO $DB_USER@localhost
IDENTIFIED BY '$DB_PASS';
FLUSH PRIVILEGES;
EOF

# setup apache configuration and complete installation
a2dissite default
a2ensite laravel
a2enmod rewrite

# init laravel configuration
cd $WEBROOT
php artisan key:generate

# setup laravel configuration
sed -i "s|'database'.*|'database' => '$DB_NAME',|" $WEBROOT/app/config/database.php
sed -i "s|'username'.*|'username' => '$DB_USER',|" $WEBROOT/app/config/database.php
sed -i "s|'password'.*|'password' => '$DB_PASS',|" $WEBROOT/app/config/database.php
sed -i "s|<h1>You have arrived.</h1>|<h1>You have arrived.</h1><h5>Laravel was installed with Turnkey-laravel</h5>|" $WEBROOT/app/views/hello.php

# install bower
npm install -g bower && npm install -g grunt-cli

# configure bower
echo '{"directory": "public/assets/vendor" }' > $WEBROOT/.bowerrc
echo '{
    "name": "Laravel 4 - Management Package",
    "version": "0.0.1",
    "dependencies": {
        "bootstrap": "~3",
        "angular-latest": "~1.2"
    }
}' > $WEBROOT/bower.json
bower install --allow-root

# stop mysql server
/etc/init.d/mysql stop

# workaround innodb crap during build!
rm -f /var/lib/mysql/ib_logfile*