#!/bin/sh -ex

VERSION='5.1'

SRC=/usr/local/src
NAME=laravel
WEBROOT=/var/www/laravel

DB_NAME=laravel
DB_USER=laravel
DB_PASS=$(mcookie)

# Download Composer
curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin

# Download Laravel
composer create-project laravel/laravel $WEBROOT $VERSION --prefer-dist

for i in storage bootstrap/cache; do
    chown -R www-data:www-data $WEBROOT/$i
done

# start mysql server
/etc/init.d/mysql start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

# stop mysql server
/etc/init.d/mysql stop

# setup apache configuration
a2dissite 000-default
a2ensite laravel
a2enmod rewrite

# setup laravel configuration
sed -i "s|'database'.*|'database' => '$DB_NAME',|" $WEBROOT/config/database.php
sed -i "s|'username'.*|'username' => '$DB_USER',|" $WEBROOT/config/database.php
sed -i "s|'password'.*|'password' => '$DB_PASS',|" $WEBROOT/config/database.php
sed -i "s|\\(<div class=\"quote\">{{ Inspiring::quote() }}</div>\\)|\1<div><h5>Laravel was installed with <a href=\"http://turnkeylinux.org\">TurnKey Linux</a>.</h5></div>|" $WEBROOT/resources/views/welcome.blade.php

