#!/bin/bash -e
# regenerate symfony secret key and mysql password

. /etc/default/inithooks

CONF=/var/www/symfony/app/config/parameters.ini
sed -i "s|secret \(.*\)|secret            = $(mcookie)|" $CONF

PASSWORD=$(mcookie)
sed -i "s|database_password \(.*\)|database_password = $(mcookie)|" $CONF

$INITHOOKS_PATH/bin/mysqlconf.py --user=symfony --pass="$PASSWORD"

